development:
  adapter: postgresql
  encoding: utf8
  database: r3adspace_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: r3adspace_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: r3adspace_production
  pool: 5
  username:
  password:
